/* config.h.  Generated by configure.  */
/* config.h.in.  Generated automatically from configure.in by autoheader.  */
#ifndef __CONFIG_H__
#define __CONFIG_H__

#define HAVE_OGG 1
#define HAVE_VORBIS 1
#define HAVE_LAME 1
// #define HAVE_X11 1
#define HAVE_COLOR 1
// #define HAVE_LIBNCURSES 1
#undef HAVE_XCURSES
#define GUI_CARBON 1
#undef GUI_NIGHTOLO 
#undef GUI_RUBIK 
// #define GUI_NIGHTOLO2 1
//#define GUI_RUBIK 1
/* #undef UI_XMLRPC */
/* #undef WITH_DMALLOC */
#define HAVE_SNDFILE 1
/* #undef HAVE_JACK */
/* Schedule in radio shows from other radio stations, MuSE channels, files, etc.  */
#define HAVE_SCHEDULER 1
/* #undef HAVE_LINUX */
#define HAVE_DARWIN 1
/* #undef HAVE_MMX */
/* #undef HAVE_SSE */
/* #undef ARCH_PPC */
/* #undef ARCH_X86 */
/* Define if you have the <dirent.h> header file. */
#define HAVE_DIRENT_H 1

/* Define if you don't have `vprintf' but do have `_doprnt.' */
/* #undef HAVE_DOPRNT */

/* Define if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define if you have the `gettimeofday' function. */
#define HAVE_GETTIMEOFDAY 1

/* Define if you have the `inet_aton' function. */
#define HAVE_INET_ATON 1

/* Define if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define if you have the <machine/soundcard.h> header file. */
/* #undef HAVE_MACHINE_SOUNDCARD_H */

/* Define if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define if you have the `nanosleep' function. */
#define HAVE_NANOSLEEP 1

/* Define if you have the <ndir.h> header file. */
/* #undef HAVE_NDIR_H */

/* Define if you have the `scandir' function. */
#define HAVE_SCANDIR 1

/* Define if you have the `select' function. */
#define HAVE_SELECT 1

/* Define if you have the `socket' function. */
#define HAVE_SOCKET 1

/* Define if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

#define HAVE_STDINT_H 1

/* #undef HAVE_DLFCN_H */

#define HAVE_INTTYPES_H 1

/* #undef HAVE_SETHOSTENT_H */

/* #undef HAVE_ENDHOSTENT_H */

#define HAVE_GETNAMEINFO 1

#define HAVE_GETADDRINFO 1

#define HAVE_INET_PTON 1

/* Define if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define if you have the <sys/dir.h> header file. */
#define HAVE_SYS_DIR_H 1

/* Define if you have the <sys/file.h> header file. */
#define HAVE_SYS_FILE_H 1

/* Define if you have the <sys/ndir.h> header file. */
/* #undef HAVE_SYS_NDIR_H */

/* Define if you have the <sys/soundcard.h> header file. */
/* #undef HAVE_SYS_SOUNDCARD_H */

/* Define if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define if you have the `vprintf' function. */
#define HAVE_VPRINTF 1

/* Name of package */
#define PACKAGE "MuSE"

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG 4

/* The size of a `short', as computed by sizeof. */
#define SIZEOF_SHORT 2

/* Define if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

#define HAVE_LRINT 1
#define HAVE_LRINTF 1
#define CPU_CLIPS_POSITIVE 1
#define CPU_CLIPS_NEGATIVE 1


/* Version number of package */
#define VERSION "0.9-cvs"

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/* here we go with some dmalloc stuff
   for memory fencing and debugging
   ================================== */
#ifdef WITH_DMALLOC
#include <stdlib.h>
#include <dmalloc.h>
#endif /* WITH_DMALLOC */
/* ========================= */

#endif
